apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbuor-website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kbuor-website
    spec:
      containers:
      - name: kbuor-website-container
        image: docker.io/kbuor/kbuor-website:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: kbuor-website
---
apiVersion: v1
kind: Service
metadata:
  name: kbuor-website-service
spec:
  selector:
    app: kbuor-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kbuor-website-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: kbuor.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kbuor-website-service
            port:
              number: 80
