apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbuor-website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kbuor-website
    spec:
      containers:
      - name: kbuor-website-container
        image: docker.io/kbuor/kbuor-website:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: kbuor-website
---
apiVersion: v1
kind: Service
metadata:
  name: kbuor-website-service
spec:
  selector:
    app: kbuor-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
